apiVersion: v1
kind: Template
metadata:
  name: adviser-imagestream
  annotations:
    description: >
      This is Thoth Adviser ImageStream for adviser with cache, this template
      is meant to be used by Bots, but could also be used by humans
    openshift.io/display-name: "Thoth: Adviser ImageStream"
    version: 0.4.1
    tags: thoth,ai-stacks,adviser
    template.openshift.io/documentation-url: https://github.com/Thoth-Station
    template.openshift.io/long-description: >
      This is Thoth Adviser ImageStream for adviser with cache, this template
      is meant to be used by Bots, but could also be used by humans
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    app: thoth
    component: adviser

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: thoth
        component: adviser
      name: adviser-cached
    spec:
      name: latest
      lookupPolicy:
        local: true
