apiVersion: v1
kind: Template
metadata:
  name: dependency-monkey
  annotations:
    description: "Thoth: Dependency Monkey"
    openshift.io/display-name: "Thoth: Dependency Monkey"
    version: 0.4.2
    tags: thoth,ai-stacks,dependency-monkey
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run recommendation logic of Thoth to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: thoth
    template: dependency-monkey
    component: dependency-monkey

parameters:
  - description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"

  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    value: "thoth-infra-stage"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - name: THOTH_DEPENDENCY_MONKEY_JOB_ID
    required: true
    description: A unique identifier of dependency monkey job run.
    displayName: Dependency monkey job id
  - name: THOTH_ADVISER_REQUIREMENTS
    required: true
    description: Raw stack requirements.
  - name: THOTH_LOG_ADVISER
    required: false
    description: Log adviser actions.
    value: INFO
  - name: THOTH_ADVISER_RUNTIME_ENVIRONMENT
    required: false
    description: Runtime environment for which the dependency monkey should be run.
  - name: THOTH_DEPENDENCY_MONKEY_STACK_OUTPUT
    required: false
    description: A URL to Amun API where the given stack should be inspected or - for stdout.
    value: "-"
  - name: THOTH_DEPENDENCY_MONKEY_REPORT_OUTPUT
    required: false
    description: A URL to remote API where a report of dependency monkey run should be submitted or - for stdout.
    value: "-"
  - name: THOTH_DEPENDENCY_MONKEY_SEED
    required: false
    description: A seed to be used for generating software stack samples.
    value: ""
  - name: THOTH_DEPENDENCY_MONKEY_DECISION
    required: false
    description:
      A decision function that should be used for generating software stack
      samples; if omitted, all software stacks will be created.
    value: "all"
  - name: THOTH_DEPENDENCY_MONKEY_DRY_RUN
    required: false
    description:
      Do not generate software stacks, just report how many software stacks
      will be generated.
    value: "0"
  - name: THOTH_AMUN_CONTEXT
    required: false
    description: A context for Amun during inspection.
    value: "-1"
  - name: THOTH_DEPENDENCY_MONKEY_COUNT
    required: false
    description: Limit number of software stacks generated by dependency monkey
    value: "-1"
  - name: THOTH_ADVISER_LIMIT_LATEST_VERSIONS
    required: false
    description: Limit number of versions starting from latest in stacks.
    displayName: Limit latest versions
    value: "-1"

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${THOTH_DEPENDENCY_MONKEY_JOB_ID}
      labels:
        app: thoth
        component: dependency-monkey
        mark: cleanup
        operator: graph-sync
        task: dependency-monkey
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: thoth
            component: dependency-monkey
            mark: cleanup
        spec:
          restartPolicy: Never
          automountServiceAccountToken: false
          containers:
            - name: dependency-monkey
              image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/adviser:${IMAGE_STREAM_TAG}"
              livenessProbe:
                # Give analyzer 30 minutes to compute results, kill it if it was not able result anything.
                tcpSocket:
                  port: 80
                initialDelaySeconds: 1800
                failureThreshold: 1
                periodSeconds: 10
              env:
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: THOTH_LOG_ADVISER
                  value: "${THOTH_LOG_ADVISER}"
                - name: THOTH_ADVISER_REQUIREMENTS
                  value: "${THOTH_ADVISER_REQUIREMENTS}"
                - name: THOTH_ADVISER_SUBCOMMAND
                  value: "dependency-monkey"
                - name: THOTH_ADVISER_RUNTIME_ENVIRONMENT
                  value: "${THOTH_ADVISER_RUNTIME_ENVIRONMENT}"
                - name: THOTH_DEPENDENCY_MONKEY_STACK_OUTPUT
                  value: "${THOTH_DEPENDENCY_MONKEY_STACK_OUTPUT}"
                - name: THOTH_DEPENDENCY_MONKEY_REPORT_OUTPUT
                  value: "${THOTH_DEPENDENCY_MONKEY_REPORT_OUTPUT}"
                - name: THOTH_DEPENDENCY_MONKEY_SEED
                  value: "${THOTH_DEPENDENCY_MONKEY_SEED}"
                - name: THOTH_DEPENDENCY_MONKEY_DECISION
                  value: "${THOTH_DEPENDENCY_MONKEY_DECISION}"
                - name: THOTH_DEPENDENCY_MONKEY_DRY_RUN
                  value: "${THOTH_DEPENDENCY_MONKEY_DRY_RUN}"
                - name: THOTH_DEPENDENCY_MONKEY_LIMIT
                  value: "${THOTH_DEPENDENCY_MONKEY_LIMIT}"
                - name: THOTH_DEPENDENCY_MONKEY_COUNT
                  value: "${THOTH_DEPENDENCY_MONKEY_COUNT}"
                - name: THOTH_AMUN_CONTEXT
                  value: "${THOTH_AMUN_CONTEXT}"
                - name: THOTH_ADVISER_LIMIT_LATEST_VERSIONS
                  value: "${THOTH_ADVISER_LIMIT_LATEST_VERSIONS}"
                - name: PROMETHEUS_PUSHGATEWAY_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: prometheus-pushgateway-host
                      name: thoth
                - name: PROMETHEUS_PUSHGATEWAY_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: prometheus-pushgateway-port
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
                - name: KNOWLEDGE_GRAPH_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: postgresql-host
                      name: thoth
                - name: KNOWLEDGE_GRAPH_PORT
                  value: "5432"
                - name: KNOWLEDGE_GRAPH_SSL_DISABLED
                  value: "1"
                - name: KNOWLEDGE_GRAPH_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-user
                - name: KNOWLEDGE_GRAPH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-password
                - name: KNOWLEDGE_GRAPH_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-name
              resources:
                limits:
                  memory: "8Gi"
                  cpu: 1
                requests:
                  memory: "8Gi"
                  cpu: 1
