apiVersion: v1
kind: Template
metadata:
  name: provenance-checker
  annotations:
    description: "Thoth: Provenance Checker"
    openshift.io/display-name: "Thoth: Provenance Checker"
    version: 0.4.2
    tags: thoth,ai-stacks,provenance-checker
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run recommendation logic of Thoth to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: thoth
    template: provenance-checker
    component: provenance-checker

parameters:
  - description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"

  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    value: "thoth-infra-stage"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - name: THOTH_PROVENANCE_CHECKER_JOB_ID
    required: true
    description: A unique identifier of provenance-checker job.
    displayName: Provenance checker id
  - name: THOTH_WHITELISTED_SOURCES
    required: false
    description: A comma separated values of URLs to whitelisted sources.
    displayName: Whitelisted sources
  - name: THOTH_ADVISER_OUTPUT
    required: false
    description: Remote where results should be send to.
  - name: THOTH_ADVISER_REQUIREMENTS
    required: false
    description: Raw stack requirements.
  - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
    required: false
    description: Fully pinned down stack.
    displayName: Locked requirements
  - name: THOTH_LOG_ADVISER
    required: false
    description: Log adviser actions.
    displayName: Log adviser actions
    value: INFO

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${THOTH_PROVENANCE_CHECKER_JOB_ID}
      labels:
        app: thoth
        component: provenance-checker
        mark: cleanup
        operator: graph-sync
        task: package-extract
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: thoth
            component: provenance-checker
            mark: cleanup
        spec:
          restartPolicy: Never
          automountServiceAccountToken: false
          containers:
            - name: provenance-checker
              image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/adviser:${IMAGE_STREAM_TAG}"
              livenessProbe:
                # Give analyzer 10 minutes to compute results, kill it if it was not able result anything.
                tcpSocket:
                  port: 80
                initialDelaySeconds: 600
                failureThreshold: 1
                periodSeconds: 10
              env:
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: THOTH_LOG_ADVISER
                  value: "${THOTH_LOG_ADVISER}"
                - name: THOTH_ADVISER_OUTPUT
                  value: "${THOTH_ADVISER_OUTPUT}"
                - name: THOTH_ADVISER_REQUIREMENTS
                  value: "${THOTH_ADVISER_REQUIREMENTS}"
                - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
                  value: "${THOTH_ADVISER_REQUIREMENTS_LOCKED}"
                - name: THOTH_WHITELISTED_SOURCES
                  value: "${THOTH_WHITELISTED_SOURCES}"
                - name: THOTH_ADVISER_SUBCOMMAND
                  value: "provenance"
                - name: PROMETHEUS_PUSHGATEWAY_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: prometheus-pushgateway-host
                      name: thoth
                - name: PROMETHEUS_PUSHGATEWAY_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: prometheus-pushgateway-port
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
                - name: KNOWLEDGE_GRAPH_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: postgresql-host
                      name: thoth
                - name: KNOWLEDGE_GRAPH_PORT
                  value: "5432"
                - name: KNOWLEDGE_GRAPH_SSL_DISABLED
                  value: "1"
                - name: KNOWLEDGE_GRAPH_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-user
                - name: KNOWLEDGE_GRAPH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-password
                - name: KNOWLEDGE_GRAPH_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-name
              resources:
                limits:
                  memory: "128Mi"
                  cpu: "500m"
                requests:
                  memory: "128Mi"
                  cpu: "500m"
